name: Check Dollar Price

on:
  repository_dispatch: # منتظر تریگر از سمت کلودفلر ورکر
    types: [trigger-bot]
  workflow_dispatch: # برای اجرای دستی در گیت‌هاب

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7 # 🟢 اصلاح شد: ارتقا به نسخه 7 برای پشتیبانی کامل از Node 24

      - name: Set up Python
        uses: actions/setup-python@v7 # 🟢 اصلاح شد: ارتقا به نسخه 7 برای پشتیبانی کامل از Node 24
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env: 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CLOUDFLARE_URL: ${{ secrets.CLOUDFLARE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python main.py
